### ISSUE TITLE
Is there a way to avoid importing duplicates when regenerating identical/updated cards?

### ISSUE THREAD

**Issue by martinjo** [repeat-space/anki-apkg-export#37]
I'm using anki-apkg-export to generate an .apkg-file from a google docs document. The idea is to regenerate the .apkg-file and re-import it whenever "cards" have been updated/added in the google docs-document. As it is now all cards, even those that are completely identical will be imported as duplicates (→ makes it hard to keep scheduling info etc). Is there a way to avoid the duplicate problem?

**Comment by yakhinvadim** [comment]
Just an idea: Anki requires the front side of a card to be unique. It looks like it's using it as ID. Are you sire your front sides are completely identical in all imports?

**Comment by ewnd9** [comment]
@amorriscode big thanks for the patch, I've just released `v4.0.3`

**Comment by amorriscode** [comment]
@ewnd9 I realized this doesn't actually resolve the issue completely. While it does update duplicate cards that get added, if the deck was previously created, it does not get edited. 

I guess we should be able to load a deck and _then_ add/update cards.

**Comment by ashlinchak** [comment]
@amorriscode How could we load a deck before updating as now its `guid` is generated based on unique value (`Date.now()`)?

**Comment by amorriscode** [comment]
Perhaps the deck could have an ID based off of the deck name instead of using `Date.now()`. I will try to do this locally and see how it goes.

**Comment by ashlinchak** [comment]
I think this is the only solution here. But I'm not sure how it will play for nested decks as in Anki we can create them by using `::` separator: `Parent::child`.
